version: "3.7"
services:
  db.cscie599.com:
    build:
      context: ./      
      dockerfile: deploy/containers/postgres/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer.cscie599.com:
    build:
      context: ./
      dockerfile: deploy/containers/adminer/Dockerfile
    depends_on:
      - db.cscie599.com
    ports:
      - 8090:8080
  webapp.cscie599.com:
    build:
      context: ./
      dockerfile: deploy/containers/webapp/Dockerfile
    depends_on:
      - db.cscie599.com
    command: ["/wait-for-it.sh", "db.cscie599.com:5432", "--timeout=120", "--strict","--", "catalina.sh","run"]
    ports:
      - 8080:8080
    volumes:
      - ./test-data:/data